name: Build mod

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build:
    name: Build mod
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'
        cache: gradle # Only cache stuff since test build action happen mostly

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew -Pnet.minecraftforge.gradle.disableUpdateChecker=true build
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ModularMachinery-CE
        path: build/libs
